apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
    org.geonode.component: conf
    org.geonode.instance.name: geonode
  creationTimestamp: null
  labels:
    io.kompose.service: data-dir-conf
  name: data-dir-conf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data-dir-conf
    spec:
      containers:
      - args:
        - /bin/true
        image: geonode/geoserver_data:latest
        name: gsconf4geonode
        resources: {}
        volumeMounts:
        - mountPath: /geoserver-data/data
          name: geonode-geoserver-data-dir
      restartPolicy: Always
      volumes:
      - name: geonode-geoserver-data-dir
        persistentVolumeClaim:
          claimName: geonode-geoserver-data-dir
status: {}
